// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wordle
{
    [WordleResourceType("wordle:index:Wordle")]
    public partial class Wordle : Pulumi.CustomResource
    {
        [Output("date")]
        public Output<string> Date { get; private set; } = null!;

        [Output("result")]
        public Output<ImmutableArray<string>> Result { get; private set; } = null!;

        [Output("word")]
        public Output<string> Word { get; private set; } = null!;


        /// <summary>
        /// Create a Wordle resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Wordle(string name, WordleArgs args, CustomResourceOptions? options = null)
            : base("wordle:index:Wordle", name, args ?? new WordleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Wordle(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("wordle:index:Wordle", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/aaronfriel/pulumi-wordle/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Wordle resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Wordle Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Wordle(name, id, options);
        }
    }

    public sealed class WordleArgs : Pulumi.ResourceArgs
    {
        [Input("word", required: true)]
        public Input<string> Word { get; set; } = null!;

        public WordleArgs()
        {
        }
    }
}
